[project]
authors = ["Sara <sara.fer.malv@gmail.com>"]
channels = ["conda-forge"]
name = "PathSingle"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.9.*"

[pypi-dependencies]
pathsingle = ">=0.2.0, <0.3"
decoupler = ">=1.9.0, <2"
ipykernel = ">=6.29.5, <7"
